[2024-03-04T17:50:03.577+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gera_dados_turbina.group_database.create_table_task scheduled__2024-03-04T17:49:00+00:00 [queued]>
[2024-03-04T17:50:03.583+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gera_dados_turbina.group_database.create_table_task scheduled__2024-03-04T17:49:00+00:00 [queued]>
[2024-03-04T17:50:03.583+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-03-04T17:50:03.583+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-03-04T17:50:03.583+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-03-04T17:50:03.592+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): group_database.create_table_task> on 2024-03-04 17:49:00+00:00
[2024-03-04T17:50:03.596+0000] {standard_task_runner.py:55} INFO - Started process 437 to run task
[2024-03-04T17:50:03.598+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gera_dados_turbina', 'group_database.create_table_task', 'scheduled__2024-03-04T17:49:00+00:00', '--job-id', '3414', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpjat2s_9w']
[2024-03-04T17:50:03.599+0000] {standard_task_runner.py:83} INFO - Job 3414: Subtask group_database.create_table_task
[2024-03-04T17:50:03.637+0000] {task_command.py:388} INFO - Running <TaskInstance: gera_dados_turbina.group_database.create_table_task scheduled__2024-03-04T17:49:00+00:00 [running]> on host f002d2097047
[2024-03-04T17:50:03.678+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=adrianolima095@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gera_dados_turbina
AIRFLOW_CTX_TASK_ID=group_database.create_table_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-04T17:49:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-04T17:49:00+00:00
[2024-03-04T17:50:03.679+0000] {sql.py:254} INFO - Executing: create table if not exists sensors 
                                        (  idtemp            varchar
                                         , powerfactor       varchar
                                         , hydraulicpressure varchar
                                         , temperature       varchar
                                         , timestamp         varchar
                                         );
                                    
[2024-03-04T17:50:03.683+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-03-04T17:50:03.804+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-03-04T17:50:03.806+0000] {sql.py:375} INFO - Running statement: create table if not exists sensors 
                                        (  idtemp            varchar
                                         , powerfactor       varchar
                                         , hydraulicpressure varchar
                                         , temperature       varchar
                                         , timestamp         varchar
                                         );
                                    , parameters: None
[2024-03-04T17:50:03.812+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=gera_dados_turbina, task_id=group_database.create_table_task, execution_date=20240304T174900, start_date=20240304T175003, end_date=20240304T175003
[2024-03-04T17:50:03.849+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-03-04T17:50:03.860+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
