[2024-02-19T21:50:32.009+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: quarta_dag.tsk3 manual__2024-02-19T21:50:31.611557+00:00 [queued]>
[2024-02-19T21:50:32.016+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: quarta_dag.tsk3 manual__2024-02-19T21:50:31.611557+00:00 [queued]>
[2024-02-19T21:50:32.016+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-19T21:50:32.016+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-02-19T21:50:32.016+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-19T21:50:32.024+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk3> on 2024-02-19 21:50:31.611557+00:00
[2024-02-19T21:50:32.027+0000] {standard_task_runner.py:55} INFO - Started process 168 to run task
[2024-02-19T21:50:32.029+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'quarta_dag', 'tsk3', 'manual__2024-02-19T21:50:31.611557+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/quartadag.py', '--cfg-path', '/tmp/tmpve4swzk5']
[2024-02-19T21:50:32.029+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask tsk3
[2024-02-19T21:50:32.062+0000] {task_command.py:388} INFO - Running <TaskInstance: quarta_dag.tsk3 manual__2024-02-19T21:50:31.611557+00:00 [running]> on host b46627357673
[2024-02-19T21:50:32.101+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=quarta_dag
AIRFLOW_CTX_TASK_ID=tsk3
AIRFLOW_CTX_EXECUTION_DATE=2024-02-19T21:50:31.611557+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-19T21:50:31.611557+00:00
[2024-02-19T21:50:32.101+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-02-19T21:50:32.102+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 5']
[2024-02-19T21:50:32.108+0000] {subprocess.py:86} INFO - Output:
[2024-02-19T21:50:37.110+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-19T21:50:37.129+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=quarta_dag, task_id=tsk3, execution_date=20240219T215031, start_date=20240219T215032, end_date=20240219T215037
[2024-02-19T21:50:37.169+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-02-19T21:50:37.188+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
